/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LoanAggSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7906414519366033196L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LoanAggSchema\",\"namespace\":\"com.example.model\",\"fields\":[{\"name\":\"AccountType\",\"type\":\"int\"},{\"name\":\"TotalCount\",\"type\":\"int\"},{\"name\":\"TotalAmount\",\"type\":\"double\"},{\"name\":\"LastMinuteCount\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LoanAggSchema> ENCODER =
      new BinaryMessageEncoder<LoanAggSchema>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LoanAggSchema> DECODER =
      new BinaryMessageDecoder<LoanAggSchema>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LoanAggSchema> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LoanAggSchema> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LoanAggSchema> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LoanAggSchema>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LoanAggSchema to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LoanAggSchema from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LoanAggSchema instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LoanAggSchema fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int AccountType;
   private int TotalCount;
   private double TotalAmount;
   private int LastMinuteCount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LoanAggSchema() {}

  /**
   * All-args constructor.
   * @param AccountType The new value for AccountType
   * @param TotalCount The new value for TotalCount
   * @param TotalAmount The new value for TotalAmount
   * @param LastMinuteCount The new value for LastMinuteCount
   */
  public LoanAggSchema(java.lang.Integer AccountType, java.lang.Integer TotalCount, java.lang.Double TotalAmount, java.lang.Integer LastMinuteCount) {
    this.AccountType = AccountType;
    this.TotalCount = TotalCount;
    this.TotalAmount = TotalAmount;
    this.LastMinuteCount = LastMinuteCount;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return AccountType;
    case 1: return TotalCount;
    case 2: return TotalAmount;
    case 3: return LastMinuteCount;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: AccountType = (java.lang.Integer)value$; break;
    case 1: TotalCount = (java.lang.Integer)value$; break;
    case 2: TotalAmount = (java.lang.Double)value$; break;
    case 3: LastMinuteCount = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'AccountType' field.
   * @return The value of the 'AccountType' field.
   */
  public int getAccountType() {
    return AccountType;
  }



  /**
   * Gets the value of the 'TotalCount' field.
   * @return The value of the 'TotalCount' field.
   */
  public int getTotalCount() {
    return TotalCount;
  }



  /**
   * Gets the value of the 'TotalAmount' field.
   * @return The value of the 'TotalAmount' field.
   */
  public double getTotalAmount() {
    return TotalAmount;
  }



  /**
   * Gets the value of the 'LastMinuteCount' field.
   * @return The value of the 'LastMinuteCount' field.
   */
  public int getLastMinuteCount() {
    return LastMinuteCount;
  }



  /**
   * Creates a new LoanAggSchema RecordBuilder.
   * @return A new LoanAggSchema RecordBuilder
   */
  public static com.example.model.LoanAggSchema.Builder newBuilder() {
    return new com.example.model.LoanAggSchema.Builder();
  }

  /**
   * Creates a new LoanAggSchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LoanAggSchema RecordBuilder
   */
  public static com.example.model.LoanAggSchema.Builder newBuilder(com.example.model.LoanAggSchema.Builder other) {
    if (other == null) {
      return new com.example.model.LoanAggSchema.Builder();
    } else {
      return new com.example.model.LoanAggSchema.Builder(other);
    }
  }

  /**
   * Creates a new LoanAggSchema RecordBuilder by copying an existing LoanAggSchema instance.
   * @param other The existing instance to copy.
   * @return A new LoanAggSchema RecordBuilder
   */
  public static com.example.model.LoanAggSchema.Builder newBuilder(com.example.model.LoanAggSchema other) {
    if (other == null) {
      return new com.example.model.LoanAggSchema.Builder();
    } else {
      return new com.example.model.LoanAggSchema.Builder(other);
    }
  }

  /**
   * RecordBuilder for LoanAggSchema instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LoanAggSchema>
    implements org.apache.avro.data.RecordBuilder<LoanAggSchema> {

    private int AccountType;
    private int TotalCount;
    private double TotalAmount;
    private int LastMinuteCount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.model.LoanAggSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.AccountType)) {
        this.AccountType = data().deepCopy(fields()[0].schema(), other.AccountType);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.TotalCount)) {
        this.TotalCount = data().deepCopy(fields()[1].schema(), other.TotalCount);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.TotalAmount)) {
        this.TotalAmount = data().deepCopy(fields()[2].schema(), other.TotalAmount);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.LastMinuteCount)) {
        this.LastMinuteCount = data().deepCopy(fields()[3].schema(), other.LastMinuteCount);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing LoanAggSchema instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.model.LoanAggSchema other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.AccountType)) {
        this.AccountType = data().deepCopy(fields()[0].schema(), other.AccountType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.TotalCount)) {
        this.TotalCount = data().deepCopy(fields()[1].schema(), other.TotalCount);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.TotalAmount)) {
        this.TotalAmount = data().deepCopy(fields()[2].schema(), other.TotalAmount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.LastMinuteCount)) {
        this.LastMinuteCount = data().deepCopy(fields()[3].schema(), other.LastMinuteCount);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'AccountType' field.
      * @return The value.
      */
    public int getAccountType() {
      return AccountType;
    }


    /**
      * Sets the value of the 'AccountType' field.
      * @param value The value of 'AccountType'.
      * @return This builder.
      */
    public com.example.model.LoanAggSchema.Builder setAccountType(int value) {
      validate(fields()[0], value);
      this.AccountType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'AccountType' field has been set.
      * @return True if the 'AccountType' field has been set, false otherwise.
      */
    public boolean hasAccountType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'AccountType' field.
      * @return This builder.
      */
    public com.example.model.LoanAggSchema.Builder clearAccountType() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'TotalCount' field.
      * @return The value.
      */
    public int getTotalCount() {
      return TotalCount;
    }


    /**
      * Sets the value of the 'TotalCount' field.
      * @param value The value of 'TotalCount'.
      * @return This builder.
      */
    public com.example.model.LoanAggSchema.Builder setTotalCount(int value) {
      validate(fields()[1], value);
      this.TotalCount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'TotalCount' field has been set.
      * @return True if the 'TotalCount' field has been set, false otherwise.
      */
    public boolean hasTotalCount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'TotalCount' field.
      * @return This builder.
      */
    public com.example.model.LoanAggSchema.Builder clearTotalCount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'TotalAmount' field.
      * @return The value.
      */
    public double getTotalAmount() {
      return TotalAmount;
    }


    /**
      * Sets the value of the 'TotalAmount' field.
      * @param value The value of 'TotalAmount'.
      * @return This builder.
      */
    public com.example.model.LoanAggSchema.Builder setTotalAmount(double value) {
      validate(fields()[2], value);
      this.TotalAmount = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'TotalAmount' field has been set.
      * @return True if the 'TotalAmount' field has been set, false otherwise.
      */
    public boolean hasTotalAmount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'TotalAmount' field.
      * @return This builder.
      */
    public com.example.model.LoanAggSchema.Builder clearTotalAmount() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'LastMinuteCount' field.
      * @return The value.
      */
    public int getLastMinuteCount() {
      return LastMinuteCount;
    }


    /**
      * Sets the value of the 'LastMinuteCount' field.
      * @param value The value of 'LastMinuteCount'.
      * @return This builder.
      */
    public com.example.model.LoanAggSchema.Builder setLastMinuteCount(int value) {
      validate(fields()[3], value);
      this.LastMinuteCount = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'LastMinuteCount' field has been set.
      * @return True if the 'LastMinuteCount' field has been set, false otherwise.
      */
    public boolean hasLastMinuteCount() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'LastMinuteCount' field.
      * @return This builder.
      */
    public com.example.model.LoanAggSchema.Builder clearLastMinuteCount() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LoanAggSchema build() {
      try {
        LoanAggSchema record = new LoanAggSchema();
        record.AccountType = fieldSetFlags()[0] ? this.AccountType : (java.lang.Integer) defaultValue(fields()[0]);
        record.TotalCount = fieldSetFlags()[1] ? this.TotalCount : (java.lang.Integer) defaultValue(fields()[1]);
        record.TotalAmount = fieldSetFlags()[2] ? this.TotalAmount : (java.lang.Double) defaultValue(fields()[2]);
        record.LastMinuteCount = fieldSetFlags()[3] ? this.LastMinuteCount : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LoanAggSchema>
    WRITER$ = (org.apache.avro.io.DatumWriter<LoanAggSchema>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LoanAggSchema>
    READER$ = (org.apache.avro.io.DatumReader<LoanAggSchema>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.AccountType);

    out.writeInt(this.TotalCount);

    out.writeDouble(this.TotalAmount);

    out.writeInt(this.LastMinuteCount);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.AccountType = in.readInt();

      this.TotalCount = in.readInt();

      this.TotalAmount = in.readDouble();

      this.LastMinuteCount = in.readInt();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.AccountType = in.readInt();
          break;

        case 1:
          this.TotalCount = in.readInt();
          break;

        case 2:
          this.TotalAmount = in.readDouble();
          break;

        case 3:
          this.LastMinuteCount = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










